[package]
name = "WIKI_BFS"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
futures = "0.3"
url = "2.4"
